"use client";

// Local persistence for Journey — Patterns (docs/TECHNICAL_ARCHITECTURE.md
// §7: "user_patterns rows, generated by the AI boundary's pattern-detection
// call, always shown with the Relevant/Not really/Tell Inner Pause more
// correction UI — corrections feed back as training signal for future
// generation, not silently discarded"). Generated results are stored so
// they're reused, not recomputed on every render (this slice's brief §10).

export type PatternStatus = "candidate" | "relevant" | "not-relevant";
export type PatternScope = "free" | "pass";

export interface PatternRecord {
  id: string;
  /** Stable key per underlying signal (e.g. "theme:sleep") — used to dedupe regeneration and to respect a prior rejection. */
  key: string;
  text: string;
  scope: PatternScope;
  status: PatternStatus;
  supportingJournalEntryIds: string[];
  supportingHighlightIds: string[];
  generatedAt: string;
  respondedAt?: string;
}

const STORAGE_KEY = "inner-pause:pattern-records";
const META_KEY = "inner-pause:pattern-generation-meta";
const EVENT_NAME = "inner-pause:pattern-records-change";

const isBrowser = () => typeof window !== "undefined";

function readAll(): PatternRecord[] {
  if (!isBrowser()) return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as PatternRecord[];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function writeAll(records: PatternRecord[]) {
  if (!isBrowser()) return;
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(records));
  window.dispatchEvent(new Event(EVENT_NAME));
}

export function listPatterns(): PatternRecord[] {
  return readAll()
    .slice()
    .sort((a, b) => b.generatedAt.localeCompare(a.generatedAt));
}

export function getPatternByKey(key: string): PatternRecord | undefined {
  return readAll().find((item) => item.key === key);
}

/**
 * Inserts a freshly-generated candidate for `key` unless one already
 * exists — and specifically never overwrites a "not-relevant" pattern, so a
 * rejected pattern stops being regenerated as if it were still trusted
 * (this slice's brief §5).
 */
export function upsertGeneratedPattern(input: {
  key: string;
  text: string;
  scope: PatternScope;
  supportingJournalEntryIds: string[];
  supportingHighlightIds: string[];
}): PatternRecord | null {
  const existing = getPatternByKey(input.key);
  if (existing) return existing.status === "not-relevant" ? null : existing;
  const record: PatternRecord = {
    id: crypto.randomUUID(),
    key: input.key,
    text: input.text,
    scope: input.scope,
    status: "candidate",
    supportingJournalEntryIds: input.supportingJournalEntryIds,
    supportingHighlightIds: input.supportingHighlightIds,
    generatedAt: new Date().toISOString(),
  };
  writeAll([record, ...readAll()]);
  return record;
}

export function setPatternStatus(id: string, status: PatternStatus) {
  writeAll(
    readAll().map((item) => (item.id === id ? { ...item, status, respondedAt: new Date().toISOString() } : item)),
  );
}

export function subscribePatterns(callback: () => void) {
  if (!isBrowser()) return () => {};
  const handler = () => callback();
  window.addEventListener(EVENT_NAME, handler);
  window.addEventListener("storage", handler);
  return () => {
    window.removeEventListener(EVENT_NAME, handler);
    window.removeEventListener("storage", handler);
  };
}

// Generation-run bookkeeping (this slice's brief §10: "periodic/on-demand
// analysis boundary," never regenerated on every render/screen visit).
const REGENERATE_AFTER_MS = 60 * 60 * 1000; // one hour — a reasonable, deterministic "periodic" cadence for local use

export function shouldRegeneratePatterns(): boolean {
  if (!isBrowser()) return false;
  const raw = window.localStorage.getItem(META_KEY);
  if (!raw) return true;
  const lastGeneratedAt = Number(raw) || 0;
  return Date.now() - lastGeneratedAt > REGENERATE_AFTER_MS;
}

export function markPatternsGenerated() {
  if (!isBrowser()) return;
  window.localStorage.setItem(META_KEY, String(Date.now()));
}
